export enum TagTypes {
  CURRENT_USER = "CURRENT_USER",
  MAIN_ACCOUNT_INFO = "MAIN_ACCOUNT_INFO",
  MAIN_ACCOUNT_TRANSECTIONS = "MAIN_ACCOUNT_TRANSECTIONS",
  ALL_AGENT_LISTS = "ALL_AGENT_LISTS",
  ALL_USER_LIST = "ALL_USER_LIST",
  SETTINGS = "SETTINGS",
  USER_REG_HISTORY = "USER_REG_HISTORY",
}
